// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: deck.proto

package com.protos;

public final class DeckProto {
  private DeckProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DeckOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.protos.Deck)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.protos.Card cards = 1;</code>
     */
    java.util.List<com.protos.CardProto.Card> 
        getCardsList();
    /**
     * <code>repeated .com.protos.Card cards = 1;</code>
     */
    com.protos.CardProto.Card getCards(int index);
    /**
     * <code>repeated .com.protos.Card cards = 1;</code>
     */
    int getCardsCount();
    /**
     * <code>repeated .com.protos.Card cards = 1;</code>
     */
    java.util.List<? extends com.protos.CardProto.CardOrBuilder> 
        getCardsOrBuilderList();
    /**
     * <code>repeated .com.protos.Card cards = 1;</code>
     */
    com.protos.CardProto.CardOrBuilder getCardsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.protos.Deck}
   */
  public static final class Deck extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.protos.Deck)
      DeckOrBuilder {
    // Use Deck.newBuilder() to construct.
    private Deck(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Deck(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Deck defaultInstance;
    public static Deck getDefaultInstance() {
      return defaultInstance;
    }

    public Deck getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Deck(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                cards_ = new java.util.ArrayList<com.protos.CardProto.Card>();
                mutable_bitField0_ |= 0x00000001;
              }
              cards_.add(input.readMessage(com.protos.CardProto.Card.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          cards_ = java.util.Collections.unmodifiableList(cards_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protos.DeckProto.internal_static_com_protos_Deck_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protos.DeckProto.internal_static_com_protos_Deck_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protos.DeckProto.Deck.class, com.protos.DeckProto.Deck.Builder.class);
    }

    public static com.google.protobuf.Parser<Deck> PARSER =
        new com.google.protobuf.AbstractParser<Deck>() {
      public Deck parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Deck(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Deck> getParserForType() {
      return PARSER;
    }

    public static final int CARDS_FIELD_NUMBER = 1;
    private java.util.List<com.protos.CardProto.Card> cards_;
    /**
     * <code>repeated .com.protos.Card cards = 1;</code>
     */
    public java.util.List<com.protos.CardProto.Card> getCardsList() {
      return cards_;
    }
    /**
     * <code>repeated .com.protos.Card cards = 1;</code>
     */
    public java.util.List<? extends com.protos.CardProto.CardOrBuilder> 
        getCardsOrBuilderList() {
      return cards_;
    }
    /**
     * <code>repeated .com.protos.Card cards = 1;</code>
     */
    public int getCardsCount() {
      return cards_.size();
    }
    /**
     * <code>repeated .com.protos.Card cards = 1;</code>
     */
    public com.protos.CardProto.Card getCards(int index) {
      return cards_.get(index);
    }
    /**
     * <code>repeated .com.protos.Card cards = 1;</code>
     */
    public com.protos.CardProto.CardOrBuilder getCardsOrBuilder(
        int index) {
      return cards_.get(index);
    }

    private void initFields() {
      cards_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getCardsCount(); i++) {
        if (!getCards(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < cards_.size(); i++) {
        output.writeMessage(1, cards_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < cards_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, cards_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.protos.DeckProto.Deck parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.DeckProto.Deck parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.DeckProto.Deck parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.DeckProto.Deck parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.DeckProto.Deck parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.protos.DeckProto.Deck parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.protos.DeckProto.Deck parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.protos.DeckProto.Deck parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.protos.DeckProto.Deck parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.protos.DeckProto.Deck parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.protos.DeckProto.Deck prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.protos.Deck}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.protos.Deck)
        com.protos.DeckProto.DeckOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protos.DeckProto.internal_static_com_protos_Deck_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protos.DeckProto.internal_static_com_protos_Deck_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protos.DeckProto.Deck.class, com.protos.DeckProto.Deck.Builder.class);
      }

      // Construct using com.protos.DeckProto.Deck.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getCardsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (cardsBuilder_ == null) {
          cards_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          cardsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protos.DeckProto.internal_static_com_protos_Deck_descriptor;
      }

      public com.protos.DeckProto.Deck getDefaultInstanceForType() {
        return com.protos.DeckProto.Deck.getDefaultInstance();
      }

      public com.protos.DeckProto.Deck build() {
        com.protos.DeckProto.Deck result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.protos.DeckProto.Deck buildPartial() {
        com.protos.DeckProto.Deck result = new com.protos.DeckProto.Deck(this);
        int from_bitField0_ = bitField0_;
        if (cardsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            cards_ = java.util.Collections.unmodifiableList(cards_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.cards_ = cards_;
        } else {
          result.cards_ = cardsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protos.DeckProto.Deck) {
          return mergeFrom((com.protos.DeckProto.Deck)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protos.DeckProto.Deck other) {
        if (other == com.protos.DeckProto.Deck.getDefaultInstance()) return this;
        if (cardsBuilder_ == null) {
          if (!other.cards_.isEmpty()) {
            if (cards_.isEmpty()) {
              cards_ = other.cards_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCardsIsMutable();
              cards_.addAll(other.cards_);
            }
            onChanged();
          }
        } else {
          if (!other.cards_.isEmpty()) {
            if (cardsBuilder_.isEmpty()) {
              cardsBuilder_.dispose();
              cardsBuilder_ = null;
              cards_ = other.cards_;
              bitField0_ = (bitField0_ & ~0x00000001);
              cardsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getCardsFieldBuilder() : null;
            } else {
              cardsBuilder_.addAllMessages(other.cards_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getCardsCount(); i++) {
          if (!getCards(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protos.DeckProto.Deck parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protos.DeckProto.Deck) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.protos.CardProto.Card> cards_ =
        java.util.Collections.emptyList();
      private void ensureCardsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          cards_ = new java.util.ArrayList<com.protos.CardProto.Card>(cards_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.protos.CardProto.Card, com.protos.CardProto.Card.Builder, com.protos.CardProto.CardOrBuilder> cardsBuilder_;

      /**
       * <code>repeated .com.protos.Card cards = 1;</code>
       */
      public java.util.List<com.protos.CardProto.Card> getCardsList() {
        if (cardsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(cards_);
        } else {
          return cardsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.protos.Card cards = 1;</code>
       */
      public int getCardsCount() {
        if (cardsBuilder_ == null) {
          return cards_.size();
        } else {
          return cardsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.protos.Card cards = 1;</code>
       */
      public com.protos.CardProto.Card getCards(int index) {
        if (cardsBuilder_ == null) {
          return cards_.get(index);
        } else {
          return cardsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.protos.Card cards = 1;</code>
       */
      public Builder setCards(
          int index, com.protos.CardProto.Card value) {
        if (cardsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCardsIsMutable();
          cards_.set(index, value);
          onChanged();
        } else {
          cardsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.Card cards = 1;</code>
       */
      public Builder setCards(
          int index, com.protos.CardProto.Card.Builder builderForValue) {
        if (cardsBuilder_ == null) {
          ensureCardsIsMutable();
          cards_.set(index, builderForValue.build());
          onChanged();
        } else {
          cardsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.Card cards = 1;</code>
       */
      public Builder addCards(com.protos.CardProto.Card value) {
        if (cardsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCardsIsMutable();
          cards_.add(value);
          onChanged();
        } else {
          cardsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.Card cards = 1;</code>
       */
      public Builder addCards(
          int index, com.protos.CardProto.Card value) {
        if (cardsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCardsIsMutable();
          cards_.add(index, value);
          onChanged();
        } else {
          cardsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.Card cards = 1;</code>
       */
      public Builder addCards(
          com.protos.CardProto.Card.Builder builderForValue) {
        if (cardsBuilder_ == null) {
          ensureCardsIsMutable();
          cards_.add(builderForValue.build());
          onChanged();
        } else {
          cardsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.Card cards = 1;</code>
       */
      public Builder addCards(
          int index, com.protos.CardProto.Card.Builder builderForValue) {
        if (cardsBuilder_ == null) {
          ensureCardsIsMutable();
          cards_.add(index, builderForValue.build());
          onChanged();
        } else {
          cardsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.Card cards = 1;</code>
       */
      public Builder addAllCards(
          java.lang.Iterable<? extends com.protos.CardProto.Card> values) {
        if (cardsBuilder_ == null) {
          ensureCardsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, cards_);
          onChanged();
        } else {
          cardsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.Card cards = 1;</code>
       */
      public Builder clearCards() {
        if (cardsBuilder_ == null) {
          cards_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          cardsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.Card cards = 1;</code>
       */
      public Builder removeCards(int index) {
        if (cardsBuilder_ == null) {
          ensureCardsIsMutable();
          cards_.remove(index);
          onChanged();
        } else {
          cardsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.Card cards = 1;</code>
       */
      public com.protos.CardProto.Card.Builder getCardsBuilder(
          int index) {
        return getCardsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.protos.Card cards = 1;</code>
       */
      public com.protos.CardProto.CardOrBuilder getCardsOrBuilder(
          int index) {
        if (cardsBuilder_ == null) {
          return cards_.get(index);  } else {
          return cardsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.protos.Card cards = 1;</code>
       */
      public java.util.List<? extends com.protos.CardProto.CardOrBuilder> 
           getCardsOrBuilderList() {
        if (cardsBuilder_ != null) {
          return cardsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(cards_);
        }
      }
      /**
       * <code>repeated .com.protos.Card cards = 1;</code>
       */
      public com.protos.CardProto.Card.Builder addCardsBuilder() {
        return getCardsFieldBuilder().addBuilder(
            com.protos.CardProto.Card.getDefaultInstance());
      }
      /**
       * <code>repeated .com.protos.Card cards = 1;</code>
       */
      public com.protos.CardProto.Card.Builder addCardsBuilder(
          int index) {
        return getCardsFieldBuilder().addBuilder(
            index, com.protos.CardProto.Card.getDefaultInstance());
      }
      /**
       * <code>repeated .com.protos.Card cards = 1;</code>
       */
      public java.util.List<com.protos.CardProto.Card.Builder> 
           getCardsBuilderList() {
        return getCardsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.protos.CardProto.Card, com.protos.CardProto.Card.Builder, com.protos.CardProto.CardOrBuilder> 
          getCardsFieldBuilder() {
        if (cardsBuilder_ == null) {
          cardsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.protos.CardProto.Card, com.protos.CardProto.Card.Builder, com.protos.CardProto.CardOrBuilder>(
                  cards_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          cards_ = null;
        }
        return cardsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.protos.Deck)
    }

    static {
      defaultInstance = new Deck(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.protos.Deck)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_protos_Deck_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_protos_Deck_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ndeck.proto\022\ncom.protos\032\ncard.proto\"\'\n\004" +
      "Deck\022\037\n\005cards\030\001 \003(\0132\020.com.protos.CardB\027\n" +
      "\ncom.protosB\tDeckProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.protos.CardProto.getDescriptor(),
        }, assigner);
    internal_static_com_protos_Deck_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_protos_Deck_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_protos_Deck_descriptor,
        new java.lang.String[] { "Cards", });
    com.protos.CardProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
