// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hero.proto

package com.protos;

public final class HeroProto {
  private HeroProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HeroOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.protos.Hero)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .com.protos.Weapon weapon = 1;</code>
     */
    boolean hasWeapon();
    /**
     * <code>required .com.protos.Weapon weapon = 1;</code>
     */
    com.protos.WeaponProto.Weapon getWeapon();
    /**
     * <code>required .com.protos.Weapon weapon = 1;</code>
     */
    com.protos.WeaponProto.WeaponOrBuilder getWeaponOrBuilder();

    /**
     * <code>required int32 armor = 2;</code>
     */
    boolean hasArmor();
    /**
     * <code>required int32 armor = 2;</code>
     */
    int getArmor();

    /**
     * <code>required .com.protos.Minion minion = 3;</code>
     */
    boolean hasMinion();
    /**
     * <code>required .com.protos.Minion minion = 3;</code>
     */
    com.protos.MinionProto.Minion getMinion();
    /**
     * <code>required .com.protos.Minion minion = 3;</code>
     */
    com.protos.MinionProto.MinionOrBuilder getMinionOrBuilder();
  }
  /**
   * Protobuf type {@code com.protos.Hero}
   */
  public static final class Hero extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.protos.Hero)
      HeroOrBuilder {
    // Use Hero.newBuilder() to construct.
    private Hero(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Hero(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Hero defaultInstance;
    public static Hero getDefaultInstance() {
      return defaultInstance;
    }

    public Hero getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Hero(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.protos.WeaponProto.Weapon.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = weapon_.toBuilder();
              }
              weapon_ = input.readMessage(com.protos.WeaponProto.Weapon.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(weapon_);
                weapon_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              armor_ = input.readInt32();
              break;
            }
            case 26: {
              com.protos.MinionProto.Minion.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = minion_.toBuilder();
              }
              minion_ = input.readMessage(com.protos.MinionProto.Minion.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(minion_);
                minion_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protos.HeroProto.internal_static_com_protos_Hero_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protos.HeroProto.internal_static_com_protos_Hero_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protos.HeroProto.Hero.class, com.protos.HeroProto.Hero.Builder.class);
    }

    public static com.google.protobuf.Parser<Hero> PARSER =
        new com.google.protobuf.AbstractParser<Hero>() {
      public Hero parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Hero(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Hero> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int WEAPON_FIELD_NUMBER = 1;
    private com.protos.WeaponProto.Weapon weapon_;
    /**
     * <code>required .com.protos.Weapon weapon = 1;</code>
     */
    public boolean hasWeapon() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.protos.Weapon weapon = 1;</code>
     */
    public com.protos.WeaponProto.Weapon getWeapon() {
      return weapon_;
    }
    /**
     * <code>required .com.protos.Weapon weapon = 1;</code>
     */
    public com.protos.WeaponProto.WeaponOrBuilder getWeaponOrBuilder() {
      return weapon_;
    }

    public static final int ARMOR_FIELD_NUMBER = 2;
    private int armor_;
    /**
     * <code>required int32 armor = 2;</code>
     */
    public boolean hasArmor() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 armor = 2;</code>
     */
    public int getArmor() {
      return armor_;
    }

    public static final int MINION_FIELD_NUMBER = 3;
    private com.protos.MinionProto.Minion minion_;
    /**
     * <code>required .com.protos.Minion minion = 3;</code>
     */
    public boolean hasMinion() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .com.protos.Minion minion = 3;</code>
     */
    public com.protos.MinionProto.Minion getMinion() {
      return minion_;
    }
    /**
     * <code>required .com.protos.Minion minion = 3;</code>
     */
    public com.protos.MinionProto.MinionOrBuilder getMinionOrBuilder() {
      return minion_;
    }

    private void initFields() {
      weapon_ = com.protos.WeaponProto.Weapon.getDefaultInstance();
      armor_ = 0;
      minion_ = com.protos.MinionProto.Minion.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasWeapon()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasArmor()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMinion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getWeapon().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getMinion().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, weapon_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, armor_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, minion_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, weapon_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, armor_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, minion_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.protos.HeroProto.Hero parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.HeroProto.Hero parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.HeroProto.Hero parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.HeroProto.Hero parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.HeroProto.Hero parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.protos.HeroProto.Hero parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.protos.HeroProto.Hero parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.protos.HeroProto.Hero parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.protos.HeroProto.Hero parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.protos.HeroProto.Hero parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.protos.HeroProto.Hero prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.protos.Hero}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.protos.Hero)
        com.protos.HeroProto.HeroOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protos.HeroProto.internal_static_com_protos_Hero_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protos.HeroProto.internal_static_com_protos_Hero_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protos.HeroProto.Hero.class, com.protos.HeroProto.Hero.Builder.class);
      }

      // Construct using com.protos.HeroProto.Hero.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getWeaponFieldBuilder();
          getMinionFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (weaponBuilder_ == null) {
          weapon_ = com.protos.WeaponProto.Weapon.getDefaultInstance();
        } else {
          weaponBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        armor_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (minionBuilder_ == null) {
          minion_ = com.protos.MinionProto.Minion.getDefaultInstance();
        } else {
          minionBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protos.HeroProto.internal_static_com_protos_Hero_descriptor;
      }

      public com.protos.HeroProto.Hero getDefaultInstanceForType() {
        return com.protos.HeroProto.Hero.getDefaultInstance();
      }

      public com.protos.HeroProto.Hero build() {
        com.protos.HeroProto.Hero result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.protos.HeroProto.Hero buildPartial() {
        com.protos.HeroProto.Hero result = new com.protos.HeroProto.Hero(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (weaponBuilder_ == null) {
          result.weapon_ = weapon_;
        } else {
          result.weapon_ = weaponBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.armor_ = armor_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (minionBuilder_ == null) {
          result.minion_ = minion_;
        } else {
          result.minion_ = minionBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protos.HeroProto.Hero) {
          return mergeFrom((com.protos.HeroProto.Hero)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protos.HeroProto.Hero other) {
        if (other == com.protos.HeroProto.Hero.getDefaultInstance()) return this;
        if (other.hasWeapon()) {
          mergeWeapon(other.getWeapon());
        }
        if (other.hasArmor()) {
          setArmor(other.getArmor());
        }
        if (other.hasMinion()) {
          mergeMinion(other.getMinion());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasWeapon()) {
          
          return false;
        }
        if (!hasArmor()) {
          
          return false;
        }
        if (!hasMinion()) {
          
          return false;
        }
        if (!getWeapon().isInitialized()) {
          
          return false;
        }
        if (!getMinion().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protos.HeroProto.Hero parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protos.HeroProto.Hero) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.protos.WeaponProto.Weapon weapon_ = com.protos.WeaponProto.Weapon.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.protos.WeaponProto.Weapon, com.protos.WeaponProto.Weapon.Builder, com.protos.WeaponProto.WeaponOrBuilder> weaponBuilder_;
      /**
       * <code>required .com.protos.Weapon weapon = 1;</code>
       */
      public boolean hasWeapon() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.protos.Weapon weapon = 1;</code>
       */
      public com.protos.WeaponProto.Weapon getWeapon() {
        if (weaponBuilder_ == null) {
          return weapon_;
        } else {
          return weaponBuilder_.getMessage();
        }
      }
      /**
       * <code>required .com.protos.Weapon weapon = 1;</code>
       */
      public Builder setWeapon(com.protos.WeaponProto.Weapon value) {
        if (weaponBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          weapon_ = value;
          onChanged();
        } else {
          weaponBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.protos.Weapon weapon = 1;</code>
       */
      public Builder setWeapon(
          com.protos.WeaponProto.Weapon.Builder builderForValue) {
        if (weaponBuilder_ == null) {
          weapon_ = builderForValue.build();
          onChanged();
        } else {
          weaponBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.protos.Weapon weapon = 1;</code>
       */
      public Builder mergeWeapon(com.protos.WeaponProto.Weapon value) {
        if (weaponBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              weapon_ != com.protos.WeaponProto.Weapon.getDefaultInstance()) {
            weapon_ =
              com.protos.WeaponProto.Weapon.newBuilder(weapon_).mergeFrom(value).buildPartial();
          } else {
            weapon_ = value;
          }
          onChanged();
        } else {
          weaponBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.protos.Weapon weapon = 1;</code>
       */
      public Builder clearWeapon() {
        if (weaponBuilder_ == null) {
          weapon_ = com.protos.WeaponProto.Weapon.getDefaultInstance();
          onChanged();
        } else {
          weaponBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .com.protos.Weapon weapon = 1;</code>
       */
      public com.protos.WeaponProto.Weapon.Builder getWeaponBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getWeaponFieldBuilder().getBuilder();
      }
      /**
       * <code>required .com.protos.Weapon weapon = 1;</code>
       */
      public com.protos.WeaponProto.WeaponOrBuilder getWeaponOrBuilder() {
        if (weaponBuilder_ != null) {
          return weaponBuilder_.getMessageOrBuilder();
        } else {
          return weapon_;
        }
      }
      /**
       * <code>required .com.protos.Weapon weapon = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.protos.WeaponProto.Weapon, com.protos.WeaponProto.Weapon.Builder, com.protos.WeaponProto.WeaponOrBuilder> 
          getWeaponFieldBuilder() {
        if (weaponBuilder_ == null) {
          weaponBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.protos.WeaponProto.Weapon, com.protos.WeaponProto.Weapon.Builder, com.protos.WeaponProto.WeaponOrBuilder>(
                  getWeapon(),
                  getParentForChildren(),
                  isClean());
          weapon_ = null;
        }
        return weaponBuilder_;
      }

      private int armor_ ;
      /**
       * <code>required int32 armor = 2;</code>
       */
      public boolean hasArmor() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 armor = 2;</code>
       */
      public int getArmor() {
        return armor_;
      }
      /**
       * <code>required int32 armor = 2;</code>
       */
      public Builder setArmor(int value) {
        bitField0_ |= 0x00000002;
        armor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 armor = 2;</code>
       */
      public Builder clearArmor() {
        bitField0_ = (bitField0_ & ~0x00000002);
        armor_ = 0;
        onChanged();
        return this;
      }

      private com.protos.MinionProto.Minion minion_ = com.protos.MinionProto.Minion.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.protos.MinionProto.Minion, com.protos.MinionProto.Minion.Builder, com.protos.MinionProto.MinionOrBuilder> minionBuilder_;
      /**
       * <code>required .com.protos.Minion minion = 3;</code>
       */
      public boolean hasMinion() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .com.protos.Minion minion = 3;</code>
       */
      public com.protos.MinionProto.Minion getMinion() {
        if (minionBuilder_ == null) {
          return minion_;
        } else {
          return minionBuilder_.getMessage();
        }
      }
      /**
       * <code>required .com.protos.Minion minion = 3;</code>
       */
      public Builder setMinion(com.protos.MinionProto.Minion value) {
        if (minionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          minion_ = value;
          onChanged();
        } else {
          minionBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .com.protos.Minion minion = 3;</code>
       */
      public Builder setMinion(
          com.protos.MinionProto.Minion.Builder builderForValue) {
        if (minionBuilder_ == null) {
          minion_ = builderForValue.build();
          onChanged();
        } else {
          minionBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .com.protos.Minion minion = 3;</code>
       */
      public Builder mergeMinion(com.protos.MinionProto.Minion value) {
        if (minionBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              minion_ != com.protos.MinionProto.Minion.getDefaultInstance()) {
            minion_ =
              com.protos.MinionProto.Minion.newBuilder(minion_).mergeFrom(value).buildPartial();
          } else {
            minion_ = value;
          }
          onChanged();
        } else {
          minionBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .com.protos.Minion minion = 3;</code>
       */
      public Builder clearMinion() {
        if (minionBuilder_ == null) {
          minion_ = com.protos.MinionProto.Minion.getDefaultInstance();
          onChanged();
        } else {
          minionBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>required .com.protos.Minion minion = 3;</code>
       */
      public com.protos.MinionProto.Minion.Builder getMinionBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getMinionFieldBuilder().getBuilder();
      }
      /**
       * <code>required .com.protos.Minion minion = 3;</code>
       */
      public com.protos.MinionProto.MinionOrBuilder getMinionOrBuilder() {
        if (minionBuilder_ != null) {
          return minionBuilder_.getMessageOrBuilder();
        } else {
          return minion_;
        }
      }
      /**
       * <code>required .com.protos.Minion minion = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.protos.MinionProto.Minion, com.protos.MinionProto.Minion.Builder, com.protos.MinionProto.MinionOrBuilder> 
          getMinionFieldBuilder() {
        if (minionBuilder_ == null) {
          minionBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.protos.MinionProto.Minion, com.protos.MinionProto.Minion.Builder, com.protos.MinionProto.MinionOrBuilder>(
                  getMinion(),
                  getParentForChildren(),
                  isClean());
          minion_ = null;
        }
        return minionBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.protos.Hero)
    }

    static {
      defaultInstance = new Hero(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.protos.Hero)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_protos_Hero_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_protos_Hero_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nhero.proto\022\ncom.protos\032\014weapon.proto\032\014" +
      "minion.proto\"]\n\004Hero\022\"\n\006weapon\030\001 \002(\0132\022.c" +
      "om.protos.Weapon\022\r\n\005armor\030\002 \002(\005\022\"\n\006minio" +
      "n\030\003 \002(\0132\022.com.protos.MinionB\027\n\ncom.proto" +
      "sB\tHeroProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.protos.WeaponProto.getDescriptor(),
          com.protos.MinionProto.getDescriptor(),
        }, assigner);
    internal_static_com_protos_Hero_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_protos_Hero_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_protos_Hero_descriptor,
        new java.lang.String[] { "Weapon", "Armor", "Minion", });
    com.protos.WeaponProto.getDescriptor();
    com.protos.MinionProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
