// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weapon.proto

package com.protos;

public final class WeaponProto {
  private WeaponProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface WeaponOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.protos.Weapon)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required int32 durability = 2;</code>
     */
    boolean hasDurability();
    /**
     * <code>required int32 durability = 2;</code>
     */
    int getDurability();

    /**
     * <code>required int32 attack = 3;</code>
     */
    boolean hasAttack();
    /**
     * <code>required int32 attack = 3;</code>
     */
    int getAttack();

    /**
     * <code>optional int32 damage = 4;</code>
     */
    boolean hasDamage();
    /**
     * <code>optional int32 damage = 4;</code>
     */
    int getDamage();
  }
  /**
   * Protobuf type {@code com.protos.Weapon}
   */
  public static final class Weapon extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.protos.Weapon)
      WeaponOrBuilder {
    // Use Weapon.newBuilder() to construct.
    private Weapon(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Weapon(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Weapon defaultInstance;
    public static Weapon getDefaultInstance() {
      return defaultInstance;
    }

    public Weapon getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Weapon(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              durability_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              attack_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              damage_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protos.WeaponProto.internal_static_com_protos_Weapon_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protos.WeaponProto.internal_static_com_protos_Weapon_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protos.WeaponProto.Weapon.class, com.protos.WeaponProto.Weapon.Builder.class);
    }

    public static com.google.protobuf.Parser<Weapon> PARSER =
        new com.google.protobuf.AbstractParser<Weapon>() {
      public Weapon parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Weapon(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Weapon> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DURABILITY_FIELD_NUMBER = 2;
    private int durability_;
    /**
     * <code>required int32 durability = 2;</code>
     */
    public boolean hasDurability() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 durability = 2;</code>
     */
    public int getDurability() {
      return durability_;
    }

    public static final int ATTACK_FIELD_NUMBER = 3;
    private int attack_;
    /**
     * <code>required int32 attack = 3;</code>
     */
    public boolean hasAttack() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 attack = 3;</code>
     */
    public int getAttack() {
      return attack_;
    }

    public static final int DAMAGE_FIELD_NUMBER = 4;
    private int damage_;
    /**
     * <code>optional int32 damage = 4;</code>
     */
    public boolean hasDamage() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 damage = 4;</code>
     */
    public int getDamage() {
      return damage_;
    }

    private void initFields() {
      name_ = "";
      durability_ = 0;
      attack_ = 0;
      damage_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDurability()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAttack()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, durability_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, attack_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, damage_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, durability_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, attack_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, damage_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.protos.WeaponProto.Weapon parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.WeaponProto.Weapon parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.WeaponProto.Weapon parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.WeaponProto.Weapon parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.WeaponProto.Weapon parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.protos.WeaponProto.Weapon parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.protos.WeaponProto.Weapon parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.protos.WeaponProto.Weapon parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.protos.WeaponProto.Weapon parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.protos.WeaponProto.Weapon parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.protos.WeaponProto.Weapon prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.protos.Weapon}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.protos.Weapon)
        com.protos.WeaponProto.WeaponOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protos.WeaponProto.internal_static_com_protos_Weapon_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protos.WeaponProto.internal_static_com_protos_Weapon_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protos.WeaponProto.Weapon.class, com.protos.WeaponProto.Weapon.Builder.class);
      }

      // Construct using com.protos.WeaponProto.Weapon.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        durability_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        attack_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        damage_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protos.WeaponProto.internal_static_com_protos_Weapon_descriptor;
      }

      public com.protos.WeaponProto.Weapon getDefaultInstanceForType() {
        return com.protos.WeaponProto.Weapon.getDefaultInstance();
      }

      public com.protos.WeaponProto.Weapon build() {
        com.protos.WeaponProto.Weapon result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.protos.WeaponProto.Weapon buildPartial() {
        com.protos.WeaponProto.Weapon result = new com.protos.WeaponProto.Weapon(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.durability_ = durability_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.attack_ = attack_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.damage_ = damage_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protos.WeaponProto.Weapon) {
          return mergeFrom((com.protos.WeaponProto.Weapon)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protos.WeaponProto.Weapon other) {
        if (other == com.protos.WeaponProto.Weapon.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasDurability()) {
          setDurability(other.getDurability());
        }
        if (other.hasAttack()) {
          setAttack(other.getAttack());
        }
        if (other.hasDamage()) {
          setDamage(other.getDamage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasDurability()) {
          
          return false;
        }
        if (!hasAttack()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protos.WeaponProto.Weapon parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protos.WeaponProto.Weapon) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private int durability_ ;
      /**
       * <code>required int32 durability = 2;</code>
       */
      public boolean hasDurability() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 durability = 2;</code>
       */
      public int getDurability() {
        return durability_;
      }
      /**
       * <code>required int32 durability = 2;</code>
       */
      public Builder setDurability(int value) {
        bitField0_ |= 0x00000002;
        durability_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 durability = 2;</code>
       */
      public Builder clearDurability() {
        bitField0_ = (bitField0_ & ~0x00000002);
        durability_ = 0;
        onChanged();
        return this;
      }

      private int attack_ ;
      /**
       * <code>required int32 attack = 3;</code>
       */
      public boolean hasAttack() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 attack = 3;</code>
       */
      public int getAttack() {
        return attack_;
      }
      /**
       * <code>required int32 attack = 3;</code>
       */
      public Builder setAttack(int value) {
        bitField0_ |= 0x00000004;
        attack_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 attack = 3;</code>
       */
      public Builder clearAttack() {
        bitField0_ = (bitField0_ & ~0x00000004);
        attack_ = 0;
        onChanged();
        return this;
      }

      private int damage_ ;
      /**
       * <code>optional int32 damage = 4;</code>
       */
      public boolean hasDamage() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 damage = 4;</code>
       */
      public int getDamage() {
        return damage_;
      }
      /**
       * <code>optional int32 damage = 4;</code>
       */
      public Builder setDamage(int value) {
        bitField0_ |= 0x00000008;
        damage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 damage = 4;</code>
       */
      public Builder clearDamage() {
        bitField0_ = (bitField0_ & ~0x00000008);
        damage_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.protos.Weapon)
    }

    static {
      defaultInstance = new Weapon(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.protos.Weapon)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_protos_Weapon_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_protos_Weapon_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014weapon.proto\022\ncom.protos\"J\n\006Weapon\022\014\n\004" +
      "name\030\001 \002(\t\022\022\n\ndurability\030\002 \002(\005\022\016\n\006attack" +
      "\030\003 \002(\005\022\016\n\006damage\030\004 \001(\005B\031\n\ncom.protosB\013We" +
      "aponProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_protos_Weapon_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_protos_Weapon_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_protos_Weapon_descriptor,
        new java.lang.String[] { "Name", "Durability", "Attack", "Damage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
